"""Lightweight size limits shared by knowledge transports and validators."""

MAX_PACK_BYTES = 10 * 1024 * 1024
MAX_PREBUILT_MANIFEST_BYTES = 2 * 1024 * 1024
MAX_PREBUILT_CHUNKS = 5_000
PREBUILT_DIMENSIONS = 256
PREBUILT_VECTOR_ROW_BYTES = PREBUILT_DIMENSIONS * 2
MAX_PREBUILT_VECTOR_BYTES = MAX_PREBUILT_CHUNKS * PREBUILT_VECTOR_ROW_BYTES
